import * as XLSX from 'xlsx';

export const importColumns = [
  ['name', 'Name'],
  ['email', 'Email'],
  ['phoneNumber', 'Phone Number'],
  ['organization', 'Organization'],
  ['country', 'Country'],
  ['city', 'City'],
  ['fullAddress', 'Full Address'],
  ['cnic', 'CNIC'],
  ['dateOfBirth', 'Date of Birth'],
  ['gender', 'Gender'],
  ['notes', 'Notes'],
  ['ngoId', 'NGO ID'],
  ['fathersName', "Father's Name"],
  ['bloodGroup', 'Blood Group'],
  ['languagesKnown', 'Languages Known'],
  ['profilePicture', 'Profile Picture'],
  ['countryOfAssignment', 'Country of Assignment'],
  ['homeCountry', 'Home Country'],
  ['organizationType', 'Organization Type'],
  ['parentOrganization', 'Parent Organization'],
  ['subOrganization', 'Sub Organization'],
  ['department', 'Department'],
  ['currentAppointment', 'Current Appointment'],
  ['designation', 'Designation'],
  ['dutyStation', 'Duty Station'],
  ['currentLocation', 'Current Location'],
  ['employmentType', 'Employment Type'],
  ['joiningDate', 'Joining Date'],
  ['contractExpiryDate', 'Contract Expiry Date'],
  ['workStatus', 'Work Status'],
  ['reportingOfficer', 'Reporting Officer'],
  ['officialPhone1', 'Official Phone 1'],
  ['officialPhone2', 'Official Phone 2'],
  ['officialEmail1', 'Official Email 1'],
  ['officialEmail2', 'Official Email 2'],
  ['personalEmail1', 'Personal Email 1'],
  ['mobileNo1', 'Mobile No 1'],
  ['mobileNo2', 'Mobile No 2'],
  ['presentAddress', 'Present Address'],
  ['permanentAddress', 'Permanent Address'],
  ['emergencyContactName', 'Emergency Contact Name'],
  ['emergencyContactRelationship', 'Emergency Contact Relationship'],
  ['emergencyContactNumber', 'Emergency Contact Number'],
  ['nationalIdNumber', 'National ID Number'],
  ['governmentIdType', 'Government ID Type'],
  ['governmentIdNumber', 'Government ID Number'],
  ['panNumber', 'PAN Number'],
  ['passportNumber', 'Passport Number'],
  ['passportIssuingCountry', 'Passport Issuing Country'],
  ['passportIssueDate', 'Passport Issue Date'],
  ['passportExpiryDate', 'Passport Expiry Date'],
  ['visaType', 'Visa Type'],
  ['visaNumber', 'Visa Number'],
  ['visaExpiryDate', 'Visa Expiry Date'],
  ['workPermitNumber', 'Work Permit Number'],
  ['workPermitExpiryDate', 'Work Permit Expiry Date'],
  ['bankName', 'Bank Name'],
  ['accountTitle', 'Account Title'],
  ['accountNumber', 'Account Number'],
  ['iban', 'IBAN'],
  ['swiftCode', 'SWIFT Code'],
  ['branchName', 'Branch Name'],
  ['salaryCurrency', 'Salary Currency'],
  ['taxIdNumber', 'Tax ID Number'],
  ['paymentMethod', 'Payment Method'],
  ['spouseName', 'Spouse Name'],
  ['spouseOccupation', 'Spouse Occupation'],
  ['numberOfDependents', 'Number of Dependents'],
  ['dependent1Name', 'Dependent 1 Name'],
  ['dependent1Relationship', 'Dependent 1 Relationship'],
  ['dependent2Name', 'Dependent 2 Name'],
  ['dependent2Relationship', 'Dependent 2 Relationship'],
  ['relationWithOfficials', 'Relation with Officials'],
  ['linkedInId', 'LinkedIn ID'],
  ['facebookId', 'Facebook ID'],
  ['twitterId', 'Twitter ID'],
  ['instagramId', 'Instagram ID'],
  ['telegramId', 'Telegram ID'],
  ['skypeId', 'Skype ID'],
  ['whatsAppNumber', 'WhatsApp Number'],
  ['signalNumber', 'Signal Number'],
  ['microsoftTeamsId', 'Microsoft Teams ID'],
  ['otherSocialMediaId', 'Other Social Media ID'],
  ['socialMediaAccountType', 'Account Type'],
  ['verificationStatus', 'Verification Status'],
  ['remarks', 'Remarks'],
  ['recordDate', 'Record Date'],
  ['recordCreatedBy', 'Record Created By'],
  ['recordCreatedDate', 'Record Created Date'],
  ['recordLastUpdatedBy', 'Record Last Updated By'],
  ['recordLastUpdatedDate', 'Record Last Updated Date'],
  ['recordVerificationStatus', 'Record Verification Status'],
  ['comments', 'Comments']
];

const headerAliases = new Map([
  ['name', 'name'],
  ['full name', 'name'],
  ['person name', 'name'],
  ['email', 'email'],
  ['email address', 'email'],
  ['phone', 'phoneNumber'],
  ['phone number', 'phoneNumber'],
  ['mobile', 'phoneNumber'],
  ['mobile number', 'phoneNumber'],
  ['organization', 'organization'],
  ['organisation', 'organization'],
  ['company', 'organization'],
  ['country', 'country'],
  ['city', 'city'],
  ['address', 'fullAddress'],
  ['full address', 'fullAddress'],
  ['cnic', 'cnic'],
  ['national id', 'cnic'],
  ['date of birth', 'dateOfBirth'],
  ['dob', 'dateOfBirth'],
  ['birth date', 'dateOfBirth'],
  ['gender', 'gender'],
  ['notes', 'notes'],
  ['note', 'notes'],

  ['our own unique id', 'ngoId'],
  ['unique id', 'ngoId'],
  ['ngo id', 'ngoId'],
  ['ngo-in-000124', 'ngoId'],
  ['father\'s name', 'fathersName'],
  ['father’s name', 'fathersName'],
  ['fathers name', 'fathersName'],
  ['father name', 'fathersName'],
  ['blood group', 'bloodGroup'],
  ['languages known', 'languagesKnown'],
  ['languages', 'languagesKnown'],
  ['profile picture', 'profilePicture'],
  ['profile photo', 'profilePicture'],
  ['photo', 'profilePicture'],
  ['country of assignment', 'countryOfAssignment'],
  ['home country', 'homeCountry'],
  ['organization type', 'organizationType'],
  ['organisation type', 'organizationType'],
  ['current parent organization', 'parentOrganization'],
  ['parent organization', 'parentOrganization'],
  ['parent organisation', 'parentOrganization'],
  ['current parent organisation', 'parentOrganization'],
  ['current sub organization', 'subOrganization'],
  ['sub organization', 'subOrganization'],
  ['sub organisation', 'subOrganization'],
  ['current sub organisation', 'subOrganization'],
  ['current department', 'department'],
  ['department', 'department'],
  ['dept', 'department'],
  ['current appointment', 'currentAppointment'],
  ['designation', 'designation'],
  ['duty station', 'dutyStation'],
  ['current location', 'currentLocation'],
  ['employment type', 'employmentType'],
  ['joining date', 'joiningDate'],
  ['join date', 'joiningDate'],
  ['contract expiry date', 'contractExpiryDate'],
  ['contract end date', 'contractExpiryDate'],
  ['work status', 'workStatus'],
  ['status', 'workStatus'],
  ['reporting officer', 'reportingOfficer'],
  ['manager', 'reportingOfficer'],
  ['salary', 'salary'],
  ['official phone 1', 'officialPhone1'],
  ['official phone 2', 'officialPhone2'],
  ['official email 1', 'officialEmail1'],
  ['official email 2', 'officialEmail2'],
  ['personal email 1', 'personalEmail1'],
  ['personal email', 'personalEmail1'],
  ['mobile no 1', 'mobileNo1'],
  ['mobile number 1', 'mobileNo1'],
  ['mobile no 2', 'mobileNo2'],
  ['mobile number 2', 'mobileNo2'],
  ['present address', 'presentAddress'],
  ['permanent address', 'permanentAddress'],
  ['emergency contact name', 'emergencyContactName'],
  ['emergency contact relationship', 'emergencyContactRelationship'],
  ['emergency relationship', 'emergencyContactRelationship'],
  ['emergency contact number', 'emergencyContactNumber'],
  ['emergency contact phone', 'emergencyContactNumber'],
  ['national identity number', 'nationalIdNumber'],
  ['aadhaar number', 'nationalIdNumber'],
  ['government issued id type', 'governmentIdType'],
  ['government id type', 'governmentIdType'],
  ['gov id type', 'governmentIdType'],
  ['government issued id number', 'governmentIdNumber'],
  ['government id number', 'governmentIdNumber'],
  ['gov id number', 'governmentIdNumber'],
  ['pan permanent account number', 'panNumber'],
  ['pan number', 'panNumber'],
  ['pan', 'panNumber'],
  ['passport number', 'passportNumber'],
  ['passport', 'passportNumber'],
  ['passport issuing country', 'passportIssuingCountry'],
  ['passport issue date', 'passportIssueDate'],
  ['passport expiry date', 'passportExpiryDate'],
  ['visa type', 'visaType'],
  ['visa number', 'visaNumber'],
  ['visa expiry date', 'visaExpiryDate'],
  ['work permit number', 'workPermitNumber'],
  ['work permit expiry date', 'workPermitExpiryDate'],
  ['bank name', 'bankName'],
  ['account title', 'accountTitle'],
  ['account number', 'accountNumber'],
  ['iban', 'iban'],
  ['swift code', 'swiftCode'],
  ['branch name', 'branchName'],
  ['salary currency', 'salaryCurrency'],
  ['tax identification number', 'taxIdNumber'],
  ['tax id', 'taxIdNumber'],
  ['payment method', 'paymentMethod'],
  ['spouse name', 'spouseName'],
  ['spouse occupation', 'spouseOccupation'],
  ['number of dependents', 'numberOfDependents'],
  ['dependents', 'numberOfDependents'],
  ['dependent 1 name', 'dependent1Name'],
  ['dependent 1 relationship', 'dependent1Relationship'],
  ['dependent 2 name', 'dependent2Name'],
  ['dependent 2 relationship', 'dependent2Relationship'],
  ['relation with any other official', 'relationWithOfficials'],
  ['relation with other officials', 'relationWithOfficials'],
  ['linkedin id profile', 'linkedInId'],
  ['linkedin id', 'linkedInId'],
  ['linkedin', 'linkedInId'],
  ['facebook id profile', 'facebookId'],
  ['facebook id', 'facebookId'],
  ['facebook', 'facebookId'],
  ['x twitter id', 'twitterId'],
  ['twitter id', 'twitterId'],
  ['twitter', 'twitterId'],
  ['x id', 'twitterId'],
  ['instagram id', 'instagramId'],
  ['instagram', 'instagramId'],
  ['telegram id', 'telegramId'],
  ['telegram', 'telegramId'],
  ['skype id', 'skypeId'],
  ['skype', 'skypeId'],
  ['whatsapp number', 'whatsAppNumber'],
  ['whatsapp', 'whatsAppNumber'],
  ['signal number', 'signalNumber'],
  ['signal', 'signalNumber'],
  ['microsoft teams id', 'microsoftTeamsId'],
  ['teams id', 'microsoftTeamsId'],
  ['teams', 'microsoftTeamsId'],
  ['other social media id', 'otherSocialMediaId'],
  ['youtube', 'otherSocialMediaId'],
  ['account type', 'socialMediaAccountType'],
  ['social media account type', 'socialMediaAccountType'],
  ['verification status', 'verificationStatus'],
  ['remarks', 'remarks'],
  ['date of record', 'recordDate'],
  ['record date', 'recordDate'],
  ['record created by', 'recordCreatedBy'],
  ['record created date', 'recordCreatedDate'],
  ['record last updated by', 'recordLastUpdatedBy'],
  ['record last updated date', 'recordLastUpdatedDate'],
  ['record verification status', 'recordVerificationStatus'],
  ['comments', 'comments']
]);

export async function importRowsFromFile(file) {
  const buffer = await file.arrayBuffer();
  const workbook = XLSX.read(buffer, { cellDates: true });
  const worksheet = workbook.Sheets[workbook.SheetNames[0]];

  if (!worksheet) return [];

  const rawRows = XLSX.utils.sheet_to_json(worksheet, { defval: '', raw: true });
  return rawRows
    .map(normalizeRow)
    .filter((row) => Object.values(row).some((value) => String(value).trim()));
}

function normalizeRow(rawRow) {
  const row = Object.fromEntries(importColumns.map(([key]) => [key, '']));

  for (const [rawKey, value] of Object.entries(rawRow)) {
    const normalizedKey = normalizeHeader(rawKey);
    const targetKey = headerAliases.get(normalizedKey);
    if (targetKey) row[targetKey] = formatValue(value, targetKey);
  }

  return row;
}

function normalizeHeader(header) {
  return String(header)
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

function formatValue(value, key) {
  if (value == null) return '';
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  if (key === 'dateOfBirth') {
    const parsed = typeof value === 'number' ? XLSX.SSF.parse_date_code(value) : null;
    if (parsed) {
      return `${parsed.y}-${String(parsed.m).padStart(2, '0')}-${String(parsed.d).padStart(2, '0')}`;
    }

    const date = new Date(value);
    if (!Number.isNaN(date.getTime())) return date.toISOString().slice(0, 10);
  }
  return String(value).trim();
}
